### PR TITLE
[DO NOT MERGE] Stringification customization

### PR DESCRIPTION
**Pull request by huangqinjin**
Demonstrate the idea of #84 .

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
I think overall I'm pretty happy with moving towards something like this. It's straightforward and elegant. The `stringifiable_container` logic is messy but was the only way I could get the desired behavior of not stringifying a container when stringifiying the contents wouldn't be useful (e.g. `[<instance of T>, <instance of T>, <instance of T>, <instance of T>, <instance of T>, <instance of T>, <instance of T>, <instance of T>, <instance of T>, <instance of T>, <instance of T>]` isn't a super helpful diagnostic). However, this might be something that can be done without. Maybe it's overcomplicating for not much benefit.

**Comment by huangqinjin** [comment]
I added an idea of container case. Can it also apply to tuple?

**Comment by jeremy-rifkin** [comment]
That's a good question, it would probably make sense to do so

**Comment by jeremy-rifkin** [comment]
I think I've gotten #86 to a decent place so I'm going to go ahead and merge and iterate from there. I think a couple todos remaining that I didn't do in my PR are: Clean up enum handling, handle error codes, handle std::expected.

**Comment by jeremy-rifkin** [comment]
I'm going to close this, happy to discuss improvements further. I think there is likely still room for improvement.

**Pull request closed without merging**
