### PR TITLE
use FetchContent for magic_enum

### PR DESCRIPTION
**Pull request by flagarde**

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
Thanks so much, sorry again for my mistake! Do you want to handle the merge or should I?

**Comment by jeremy-rifkin** [comment]
Ok, I verified I know how to push properly to a contributor branch so I will take the liberty of merging

**Comment by jeremy-rifkin** [comment]
I think the test failures are superficial. I'll merge and tweak as needed. Thanks so much for the contribution and apologies again for my clumsiness!

**Comment by jeremy-rifkin** [comment]
Ok, got everything working. One thing I had to do was link magic_enum::magic_enum publicly, does that sound alright to you?

**Comment by flagarde** [comment]
Yes PUBLIC seems better as you use it on templates

**Pull request merged**
