### PR TITLE
Add: Support for MacOS

### PR DESCRIPTION
**Pull request by spnda**
This is experimental support for MacOS, which mainly bases on properly loading Mach-O binaries
and using NS functions for getting some data. Note however, that this currently does not work as
addr2line does not exist on Mac systems by default. Gonna work more on this in the next few days,
just leaving this here if anyone else needs the changes :)

### CODE REVIEW

**Comment by SK83RJOSH** [comment]
Any progress on this? I'm hoping to use this library in a native blender plugin, and unfortunately, that means MacOS is high on my priority list. 🙂

**Comment by jeremy-rifkin** [comment]
I still need to find a way to get access to a mac to test on... Or maybe it's time for this library to use a proper stack trace implementation...

**Comment by spnda** [comment]
Yeah getting symbol names is the only issue I have. I couldn't find a replacement for addr2line that is installed by default on macOS, so the address resolution simply fails currently. I have no idea how to fix that so i've just left this open.

**Comment by SK83RJOSH** [comment]
> maybe it's time for this library to use a proper stack trace implementation

I'd be curious if there's a nice FOSS solution out there, might help you ditch the addr2line stuff? In any case I've put asserts on the backburner so there's no rush on my end. :)

**Comment by jeremy-rifkin** [comment]
Hey, yes! Both the stack trace and libc++ regex issues have come up again recently. As soon as I get some time, hopefully this coming week, I will tackle these and it should enable mac support. I'm going to close this PR for now since I'm hoping to move away from addr2line entirely.

**Comment by jeremy-rifkin** [comment]
Thank you everyone for the interest and contributions!

> also I have a question: is there any way that I can still use libassert on windows, linux and for osx do a fallback to standard assert?

It would be possible to do this as an interim solution for most cases. Assert/verify/assume do return values to allow use such as `float f = *assert(get_param());`, which would complicate things. It might also be possible to just omit stack trace generation completely on mac for the moment to get things compiling until we can properly address the root causes.

**Comment by spnda** [comment]
> Hey, yes! Both the stack trace and libc++ regex issues have come up again recently. As soon as I get some time, hopefully this coming week, I will tackle these and it should enable mac support. I'm going to close this PR for now since I'm hoping to move away from addr2line entirely.

Well that wasn't the whole point of this PR; there's still other stuff in here required for Mac support. This PR actually has not implemented anything with addr2line yet. Getting the proper symbols with dlsym also seemed like it wasn't trivial, but I don't remember exactly what my issue was with that. I'd still be happy to work on this, unless you have a different (and better) idea now (with nearly a full year gone by).

**Comment by wAuner** [comment]
Any updates on macOS support? I'd really like to give it a try.

**Comment by jeremy-rifkin** [comment]
Yes! I’m working on pulling all the stack trace stuff into another library and spnda is helping me get mac support going there! So hopeful soon :)

**Comment by jeremy-rifkin** [comment]
Contributions and help ironing out support on various systems would be very welcome if you’re interested! The repo is at https://github.com/jeremy-rifkin/cpptrace

**Comment by spnda** [comment]
The main issue why this didn't work was #15. The rest more or less worked iirc, but thats now also part of cpptrace so that's irrelevant.

**Comment by wAuner** [comment]
I'd be happy to help. What can I do to help?

**Comment by wAuner** [comment]
Would it be possible to get macOS support w/o stacktrace support in the meantime? Stacktraces are nice for sure, but I could do without them in the meantime. Once you trigger `abort()` macOS (usually) creates a crash report which contains stacktraces for all threads.

**Comment by wAuner** [comment]
ok thanks for the explanation. I've looked at the regex problem with libc++, but I think I'll leave that one for the pros. Meddling in the STL doesn't promise much fun. Wouldn't be the first issue I've seen there either.

**Comment by jeremy-rifkin** [comment]
Thanks @spnda and @wAuner, and thanks for the interest in helping! I'm hoping to get basic cpptrace functionality ironed out asap (help with testing on various machines is a massive help at the moment). Then to integrate into libassert shortly there after.

**Comment by jeremy-rifkin** [comment]
For the regex issue spnda mentioned there's probably a way to rephrase the regex to workaround the libc++ bug. Or I'll just replace std <regex> completely.

**Pull request closed without merging**
